export const LOGOUT_EMPLOYEE_ORDERS_REQUEST = 'LOGOUT_EMPLOYEE_ORDERS_REQUEST';
export const LOGOUT_EMPLOYEE_ORDERS_SUCCESS = 'LOGOUT_EMPLOYEE_ORDERS_SUCCESS';
export const LOGOUT_EMPLOYEE_ORDERS_FAIL = 'LOGOUT_EMPLOYEE_ORDERS_FAIL';

